# Site settings
title: Alessio Crippa
email: alessio.crippa@gmail.com
description: >
    © Alessio Crippa. Powered by <a href=http://jekyllrb.com/>jekyll</a>. 
    Source available on <a href=https://github.com/alecri/alecri.github.io>github</a>.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: AlessioCrippa
github_username:  alecri

# Build settings
markdown: kramdown

